name: PR Labeler
on:
  # Runs workflow when activity on a PR in the workflow's repository occurs.
  pull_request_target:

jobs:
  triage:
    permissions:
      contents: read
      pull-requests: write

    name: Assign labels
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - uses: actions/labeler@v4
      with:
        # Auto-include paths starting with dot (e.g. .github)
        dot: true
        # Remove labels when matching files are reverted or no longer changed by the PR
        sync-labels: true
